// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAI.Data;

#nullable disable

namespace Anacreon.Migrations
{
    [DbContext(typeof(AIContext))]
    [Migration("20260120102045_EpistemicRefactor")]
    partial class EpistemicRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SmartAI.Models.CodeInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeSnippet")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suggestion")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("TradeOffs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Language");

                    b.ToTable("CodeInsights");
                });

            modelBuilder.Entity("SmartAI.Models.Concept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentConceptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentConceptId");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("SmartAI.Models.ConceptProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("ConceptProperties");
                });

            modelBuilder.Entity("SmartAI.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("SmartAI.Models.Fact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ValidationSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("Status");

                    b.HasIndex("Subject");

                    b.HasIndex("ValidationSessionId");

                    b.HasIndex("Subject", "Relation");

                    b.ToTable("Facts");
                });

            modelBuilder.Entity("SmartAI.Models.FactConflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConfidenceDifference")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactBId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Resolution")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactAId");

                    b.HasIndex("FactBId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("Subject");

                    b.ToTable("FactConflicts");
                });

            modelBuilder.Entity("SmartAI.Models.FactHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FactId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NewConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("NewObject")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewRelation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewSubject")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("PreviousConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("PreviousObject")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousRelation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousSubject")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("FactId");

                    b.ToTable("FactHistory");
                });

            modelBuilder.Entity("SmartAI.Models.FactSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawContent")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<double>("TrustWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5);

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactId");

                    b.HasIndex("Type");

                    b.ToTable("FactSources");
                });

            modelBuilder.Entity("SmartAI.Models.Instance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("SmartAI.Models.InstanceProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("InstanceProperties");
                });

            modelBuilder.Entity("SmartAI.Models.ValidationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatesPresented")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactsRejected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("UserId");

                    b.ToTable("ValidationSessions");
                });

            modelBuilder.Entity("SmartAI.Models.Concept", b =>
                {
                    b.HasOne("SmartAI.Models.Concept", "ParentConcept")
                        .WithMany()
                        .HasForeignKey("ParentConceptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentConcept");
                });

            modelBuilder.Entity("SmartAI.Models.ConceptProperty", b =>
                {
                    b.HasOne("SmartAI.Models.Concept", "Concept")
                        .WithMany("Properties")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("SmartAI.Models.Fact", b =>
                {
                    b.HasOne("SmartAI.Models.ValidationSession", null)
                        .WithMany("RelatedFacts")
                        .HasForeignKey("ValidationSessionId");
                });

            modelBuilder.Entity("SmartAI.Models.FactConflict", b =>
                {
                    b.HasOne("SmartAI.Models.Fact", "FactA")
                        .WithMany()
                        .HasForeignKey("FactAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAI.Models.Fact", "FactB")
                        .WithMany()
                        .HasForeignKey("FactBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FactA");

                    b.Navigation("FactB");
                });

            modelBuilder.Entity("SmartAI.Models.FactHistory", b =>
                {
                    b.HasOne("SmartAI.Models.Fact", "Fact")
                        .WithMany("History")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fact");
                });

            modelBuilder.Entity("SmartAI.Models.FactSource", b =>
                {
                    b.HasOne("SmartAI.Models.Fact", "Fact")
                        .WithMany("Sources")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fact");
                });

            modelBuilder.Entity("SmartAI.Models.Instance", b =>
                {
                    b.HasOne("SmartAI.Models.Concept", "Concept")
                        .WithMany("Instances")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("SmartAI.Models.InstanceProperty", b =>
                {
                    b.HasOne("SmartAI.Models.Instance", "Instance")
                        .WithMany("Properties")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("SmartAI.Models.Concept", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("SmartAI.Models.Fact", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("SmartAI.Models.Instance", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("SmartAI.Models.ValidationSession", b =>
                {
                    b.Navigation("RelatedFacts");
                });
#pragma warning restore 612, 618
        }
    }
}
